title: Turma CC17
info: >-
    Site de organização da turma de Ciência da Computação do ano de 2017.
    Universidade Federal de Alagoas, campus Arapiraca.
baseurl: ""
url: localhost:4000

social:
    facebook:
    github:
    instagram:
    medium:
    snapchat:
    twitter:

author:
    name: tkovs
    email: tkovs@outlook.com
    phone: (82) 98149-8525
    address: Arapiraca, AL - Brasil

# Build settings
markdown: kramdown
plugins:
    - jekyll-feed
timezone: America/Maceio

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
